server:
  error:
    include-exception: false
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parking
    username: admin
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
